version: '3.8'

services:
  database:
    image: postgres:15
    restart: always
    ports:
      - "${DATASOURCE_PORT}:5432"
    environment:
      POSTGRES_DB: conrode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
